### ISSUE TITLE
Bring back Stone Cold Lock of the Century of the Week

### ISSUE THREAD

**Issue by elfurbe** [SASEliminator/issues#9]
A previous incarnation of Eliminator highlighted a "Stone Cold Lock of the Week" and also a "Shoe In of the Week" (I do not know the difference between those, further research required). Bring that back.

**Comment by reaperhulk** [comment]
It was a Simpsons joke from Lisa the Greek.

[lock of the week](https://frinkiac.com/caption/S03E14/248482)
[shoe-in of the week](https://frinkiac.com/caption/S03E14/258225)

And who could forget the [gambletron](https://frinkiac.com/caption/S03E14/269253)

These 3 items were on a right sidebar on the front page in the original PHP codebase that was retired 5-7 years ago. Lock of the week was whatever my eliminator pick was, shoe-in was a friend's, and gambletron was a crazy algorithm that attempted to build a power ranking of all the teams based on the scraped statistics and picked whatever the team with the biggest positive differential was (e.g. the 3rd ranked team playing the 31st ranked team).

There was a brief attempt to figure out what a DSL for writing your own power ranking algorithms would look like (to allow users to invent their own and compete on who could write the best model), but 7 years ago me couldn't figure out how to make that performant enough to be useful.

**Comment by elfurbe** [comment]
You have saved me a googling and for that you are to be commended.

This sounds like solid comedy. We'll consider how these things might be implemented and also what data sources we might use to populate them.

**Comment by elfurbe** [comment]
Confusingly, we actually did this. I'm sure we'll fail to keep it updated, but the framework is there and our shame will be apparent. Closing for great victory!
